### ISSUE TITLE
Thrust Load Cell Calibration

### ISSUE THREAD

**Issue by hToupin** [UVicRocketry/PDP-Monitoring-System#15]
# Description
Very noisy singal from thrust load cell might need recalibration.

**Comment by jjderooy** [comment]
This has now been resolved. It is suspected that the boost converter supplying 10V to the pressure transducers was creating a lot of noise that affected other sensors as well (including the load cell). Removing the boost converter, the thrust load cell gives accurate values tested with my body weight with acceptable noise (+-10N or so at idle).
